# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'donet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**\PostmanDelivers.API.csproj'
    arguments: '--configuration Release'

- task: CmdLine@2
  inputs:
    script: |
      cd $(Build.SourcesDirectory)
      dir /s
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\PostmanDelivers.API\bin\Release\netcoreapp2.2\publish\'
    ArtifactName: 'drop'
    publishLocation: 'Container'