# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'donet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**\PostmanDelivers.API.csproj'
    arguments: '--configuration Release'

- task: CmdLine@2
  inputs:
    script: |
      cd $(Build.SourcesDirectory)
      dir /s
- task: PublishBuildArtifacts@1
  displayName: 'Publish API'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\PostmanDelivers.API\bin\Release\netcoreapp2.2\publish.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish postman globals'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\Postman Delivers.postman_globals.json'
    ArtifactName: 'globals'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish azure env'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\PostmandDelivers Azure.postman_environment.json'
    ArtifactName: 'azure environment'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish test collection'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\X Wins With Tests.postman_collection.json'
    ArtifactName: 'test collection'
    publishLocation: 'Container'